export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

  USER_INFO_FETCH: "USER_INFO_FETCH",
  USER_INFO_FETCH_SUCCESS: "USER_INFO_FETCH_SUCCESS",
  USER_INFO_FETCH_FAILAURE: "USER_INFO_FETCH_FAILAURE",
  USER_INFO_FETCH_UNAUTHORIZED: "USER_INFO_FETCH_UNAUTHORIZED",

  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
};
